run: c.out cpp.out Ejercicio3.class
c.out:
	g++ Ejercicio3.cpp -o c.out -DCSTRINGS
cpp.out:
	g++ Ejercicio3.cpp -o cpp.out
Ejercicio3.class:
	javac Ejercicio3.java
clean:
	rm c.out
	rm cpp.out
	rm Ejercicio3.class
